name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: b0n60

      - name: Push result back
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: output
          force: true
